server:
  port: 8100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      default:
        max-attempts: 5
        wait-duration: 2s
        enable-exponential-backoff: true

spring:
  application:
    name: book-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/book_service?useTimeZone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/
    user: root
    password: 12345678
    schemas:
      - book_service

springdoc:
  api-docs:
    path: book-service/v3/api-docs